services:
  #  =================================================================
  #  Discovery Server (Eureka)
  #  Eureka dùng cho local thôi
  #  =================================================================
  discovery-server:
    image: huynhducphu2502/tea4life-discovery-server:latest
    container_name: tea4life-discovery-server-container
    deploy:
      resources:
        limits:
          memory: 256M
    #    depends_on:
    #      keycloak:
    #        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1",
        ]
      start_period: 10s
      retries: 10
      timeout: 5s
      interval: 10s
    ports:
      - "8761:8761"
    environment:
      EUREKA_INSTANCE_HOSTNAME: ${EUREKA_INSTANCE_HOSTNAME}
    networks:
      - tea4life-network

  #  =================================================================
  #  Storage Service
  #  =================================================================
  storage-service:
    image: huynhducphu2502/tea4life-storage-service:latest
    container_name: tea4life-storage-service-container
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1",
        ]
      start_period: 10s
      retries: 10
      timeout: 5s
      interval: 10s
    ports:
      - "8081:8080"
    environment:
      # AWS S3
      STORAGE_SERVICE_S3_ACCESS_KEY: ${STORAGE_SERVICE_S3_ACCESS_KEY}
      STORAGE_SERVICE_S3_SECRET_KEY: ${STORAGE_SERVICE_S3_SECRET_KEY}
      STORAGE_SERVICE_S3_REGION: ${STORAGE_SERVICE_S3_REGION}
      STORAGE_SERVICE_S3_BUCKET_NAME: ${STORAGE_SERVICE_S3_BUCKET_NAME}
      # Kafka
      KAFKA_BOOTSTRAP_SERVER: ${KAFKA_BOOTSTRAP_SERVER}
      STORAGE_SERVICE_KAFKA_CONSUMER_GROUP_ID: ${STORAGE_SERVICE_KAFKA_CONSUMER_GROUP_ID}
      STORAGE_DELETE_FILE_TOPIC: ${STORAGE_DELETE_FILE_TOPIC}
      # Discovery Server
      EUREKA_CLIENT_ENABLED: true
      EUREKA_DISCOVERY_ENABLED: true
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    networks:
      - tea4life-network

  #  =================================================================
  #  Gateway Server [Priority Order 6]
  #  =================================================================
  gateway-server:
    image: huynhducphu2502/tea4life-gateway-server:latest
    container_name: tea4life-gateway-server-container
    deploy:
      resources:
        limits:
          memory: 320M
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1",
        ]
      start_period: 10s
      retries: 10
      timeout: 5s
      interval: 10s
    ports:
      - "8888:8888"
    environment:
      # Keycloak
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      KEYCLOAK_JWT_SET_URI: ${KEYCLOAK_JWT_SET_URI}
      # CORS
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      # Discovery Server
      EUREKA_CLIENT_ENABLED: true
      EUREKA_DISCOVERY_ENABLED: true
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
      # Service URL
      STORAGE_SERVICE_URL: ${STORAGE_SERVICE_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      PRODUCT_SERVICE_URL: ${PRODUCT_SERVICE_URL}
      BLOG_SERVICE_URL: ${BLOG_SERVICE_URL}
      ORDER_SERVICE_URL: ${ORDER_SERVICE_URL}
      LOGISTICS_SERVICE_URL: ${LOGISTICS_SERVICE_URL}
      AUDIT_SERVICE_URL: ${AUDIT_SERVICE_URL}
      WORKFLOW_SERVICE_URL: ${WORKFLOW_SERVICE_URL}
      RECOMMENDATION_SERVICE_URL: ${RECOMMENDATION_SERVICE_URL}
    networks:
      - tea4life-network

volumes:
  kafka_data:

networks:
  tea4life-network:
    driver: bridge
